<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>Benachrichtigung &uuml;ber die Sperrung Ihres Kontos</title>
    <style>
        body {
            font-family: "Jost", sans-serif;
            font-size: 1.6rem;
            font-weight: 400;
            line-height: 2.8rem;
            color: #000000;
            background-color: #ffffff;
            padding: 20px;
        }

        h2 {
            font-size: 2.2rem;
            line-height: 2.6rem;
            color: #061738;
            margin-bottom: 20px;
        }

        h3 {
            font-size: 1.7rem;
            line-height: 2.4rem;
            color: #ee2761;
            margin-bottom: 15px;
        }

        a {
            color: rgb(11, 94, 215);
            text-decoration: none;
        }
    </style>
</head>
<body>
<h2>Guten Tag, ${firstName} ${lastName}!</h2>

<h3>Wir m&ouml;chten Sie informieren, dass Ihr Konto vor&uuml;bergehend gesperrt wurde.</h3>

<p>Falls Sie Fragen zur Sperrung Ihres Kontos haben, z&ouml;gern Sie bitte nicht, sich an die Administratoren zu wenden. Sie k&ouml;nnen uns &uuml;ber die folgenden Kontaktdaten erreichen:</p>

<p><a href="http://allcom.itvm.com.ua:5173/contact">Kontakt</a></p>

<p>Vielen Dank f&uuml;r Ihr Verst&auml;ndnis.</p>

<p>Mit freundlichen Gr&uuml;&szlig;en,<br> Allcom </p>
</body>
</html>
