<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrierung auf der Allcom-Websiten</title>
    <style>
        body {
            font-family: "Jost", sans-serif;
            font-size: 1.6rem;
            font-weight: 400;
            line-height: 2.8rem;
            color: #000000;
            background-color: #ffffff;
            padding: 20px;
        }

        h2 {
            font-size: 2.2rem;
            line-height: 2.6rem;
            color: #061738;
            margin-bottom: 20px;
        }

        h3 {
            font-size: 1.7rem;
            line-height: 2.4rem;
            color: #ee2761;
            margin-bottom: 15px;
        }

        a {
            color: rgb(11, 94, 215);
            text-decoration: none;
        }
    </style>
</head>
<body>
<h2>Guten Tag, ${firstName} ${lastName}!</h2>

<h3>Vielen Dank für die Registrierung auf unserer Auktionsplattform! Wir freuen uns, Sie als neues Mitglied begrüßen zu dürfen.</h3>

<p>Um Ihre Teilnahme zu aktivieren, bitten wir Sie, alle erforderlichen Unterlagen vorzulegen und einen Vertrag in unserem Büro zu unterzeichnen. Ihre Anmeldung wird nach erfolgreicher Prüfung und Abschluss dieser Schritte aktiviert.</p>

<p>Bitte besuchen Sie unser Büro unter folgendem <a href="#">Link</a>, um einen Termin zu vereinbaren und den Aktivierungsprozess abzuschließen.</p>

<p>Wir stehen Ihnen bei Fragen gerne zur Verfügung. Vielen Dank für Ihr Vertrauen in unsere Plattform.</p>

<p>Mit freundlichen Grüßen,<br> Allcom </p>
</body>
</html>